version: "3.4"

services:

  nginx:
    container_name: laravel_nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    networks:
      - laravel_network
    ports:
      - "1212:80"
      - "1211:443"

  mysql:
    container_name: laravel_mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "laravel_mysql"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "1210:3306"
    networks:
      - laravel_network

  php:
    container_name: laravel_php
    image: marcelofabianov/php-dbs
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    ports:
      - "1209:9000"

networks:
  laravel_network:
    driver: bridge
